[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4"
markdown = "1.0.0"
pyo3 = "0.25.1"
reqwest = "0.12.20"
serde = "1.0.219"
serde_derive = "1.0.219"
