[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4"
git2 = "0.20.2"
pest = "2.8.1"
pest_derive = "2.8.1"
rusqlite = "0.37.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
